In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Load Data

In [4]:
customers = pd.read_csv("customers.csv")

transactions = pd.read_csv("transactions.csv")

loans = pd.read_csv("loans.csv")

branches = pd.read_csv("branches.csv")

cards = pd.read_csv("credit_cards.csv")

fds = pd.read_csv("fixed_deposits.csv")

In [9]:
customers.shape

# transactions.shape

# loans.shape

# branches.shape

# cards.shape

# fds.shape

(15000, 10)

first 5 rows

In [10]:
customers.head()

,CustomerID,Age,Gender,City,Occupation,AnnualSalary,CreditScore,AccountBalance,CustomerTenureYears,BranchID
0,100001,71,Female,Delhi,Salaried,2437005,642,2907344,0,B019
1,100002,69,Female,Lucknow,Government,1151182,733,3385616,29,B034
2,100003,45,Male,Lucknow,Retired,2639833,808,4403969,0,B029
3,100004,28,Male,Bengaluru,Self Employed,2435236,761,3012595,7,B037
4,100005,27,Male,Bhopal,Salaried,4652023,769,1007542,22,B020

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           15000 non-null  int64
 1   Age                  15000 non-null  int64
 2   Gender               15000 non-null  object
 3   City                 15000 non-null  object
 4   Occupation           14523 non-null  object
 5   AnnualSalary         15000 non-null  int64
 6   CreditScore          15000 non-null  int64
 7   AccountBalance       15000 non-null  int64
 8   CustomerTenureYears  15000 non-null  int64
 9   BranchID             15000 non-null  object
dtypes: int64(6), object(4)
memory usage: 1.1+ MB

In [14]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  250000 non-null  int64
 1   CustomerID     250000 non-null  int64
 2   Date           250000 non-null  object
 3   BranchID       250000 non-null  object
 4   Type           250000 non-null  object
 5   Channel        250000 non-null  object
 6   Amount         250000 non-null  int64
dtypes: int64(3), object(4)
memory usage: 13.4+ MB

IS NULL

In [15]:
customers.isnull().sum()

CustomerID               0
Age                      0
Gender                   0
City                     0
Occupation             477
AnnualSalary             0
CreditScore              0
AccountBalance           0
CustomerTenureYears      0
BranchID                 0
dtype: int64

missing percentage

In [18]:
customers.isnull().mean()*100

CustomerID             0.00
Age                    0.00
Gender                 0.00
City                   0.00
Occupation             3.18
AnnualSalary           0.00
CreditScore            0.00
AccountBalance         0.00
CustomerTenureYears    0.00
BranchID               0.00
dtype: float64

# Fill Missing Occupation

In [21]:
customers['Occupation'].mode()
customers['Occupation'] = customers['Occupation'].fillna(

customers['Occupation'].mode()[0]

)

In [22]:
customers.isnull().sum()

CustomerID             0
Age                    0
Gender                 0
City                   0
Occupation             0
AnnualSalary           0
CreditScore            0
AccountBalance         0
CustomerTenureYears    0
BranchID               0
dtype: int64

check duplicate rows

In [23]:
customers.duplicated().sum()

np.int64(0)

In [24]:
transactions.duplicated().sum()

loans.duplicated().sum()

np.int64(0)

# negative transactions

In [ ]:
transactions[transactions['Amount']<0]

len(transactions[transactions['Amount']<0])

# remove

0

In [33]:
transactions = transactions[transactions['Amount']>=0]
transactions.shape

(249400, 7)

#convert date

In [35]:
transactions['Date']=pd.to_datetime(transactions['Date'])

In [36]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249400 entries, 0 to 249999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  249400 non-null  int64
 1   CustomerID     249400 non-null  int64
 2   Date           249400 non-null  datetime64[ns]
 3   BranchID       249400 non-null  object
 4   Type           249400 non-null  object
 5   Channel        249400 non-null  object
 6   Amount         249400 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 15.2+ MB

In [37]:
transactions['Year']=transactions['Date'].dt.year
transactions['Month']=transactions['Date'].dt.month
transactions['Month_Name']=transactions['Date'].dt.month_name()

In [38]:
transactions.head()

,TransactionID,CustomerID,Date,BranchID,Type,Channel,Amount,Year,Month,Month_Name
0,1,109672,2024-03-23,B023,Deposit,UPI,651499,2024,3,March
1,2,106047,2025-05-12,B005,Deposit,UPI,1177900,2025,5,May
2,3,109137,2023-04-21,B038,Withdrawal,NetBanking,37871,2023,4,April
3,4,102122,2026-05-18,B004,Deposit,UPI,1035154,2026,5,May
4,5,102406,2026-05-29,B008,Withdrawal,UPI,605737,2026,5,May

In [39]:
customers.to_csv('customers_clean.csv',index=False)

In [40]:
transactions.to_csv('transactions_clean.csv',index=False)
loans.to_csv('loans_clean.csv',index=False)